pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                bat 'mvn -f java-tomcat-sample-docker/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Create Tomcat Docker Image'){
            steps {
                bat "cd"
                bat "dir"
                bat "docker build -t tomcatsamplewebapp:${env.BUILD_ID} ./java-tomcat-sample-docker"
            }
        }

        stage('Push Image to Docker Hub'){
            steps{
                echo 'Pushing image to DockerHub'
                timeout(time: 5, unit: 'DAYS'){
                    input message: 'Do you want to push this image to DockerHub'
                }
                bat "docker tag tomcatsamplewebapp:${env.BUILD_ID} fireboy30/tomcatsamplewebapp:${env.BUILD_ID}"
                bat "docker push fireboy30/tomcatsamplewebapp:${env.BUILD_ID}"
            }
        }

    }
}